### ISSUE TITLE
Transparent background on favicon

### ISSUE THREAD

**Issue by amyvbenson** [frontendnorth/fen#15]
Looks a bit weird on a dark background at the mo
<img width="227" alt="screenshot 2019-01-24 at 13 31 10" src="https://user-images.githubusercontent.com/2060033/51681449-81a74500-1fdc-11e9-84a2-dff23031a7fa.png">

**Comment by jparcher** [comment]
Fixed with this PR https://github.com/frontendnorth/fen/pull/28
