### ISSUE TITLE
Venue & travel

### ISSUE THREAD

**Issue by iparr** [frontendnorth/fen#35]
## Transport

- Train
- Bus
- Taxis
- Parking
- …

## Accomodation

Hotels

## Accessibility to the venue

- Wheelchair access
- Help on the day

### Breast-feeding friendly

- Yes / no - locations

## What else is there to do in Sheffield?

- Pubs / bars
- Galleries
- Museums
- Shows
- Parks
- Walkies out into the peaks

**Comment by chicgeek** [comment]
List to merge:

EAT
- Kommune
- Cutlery Works
- <find list of local places: our fave places?>

SLEEP
- list of (preferred / discounted) hotels

DO
- Winter Gardens / Millennium Gallery
- https://www.ourfaveplaces.co.uk/whats-on/
- https://streetartsheffield.com/

COWORKING DAY RATES
- https://shefftechparks.com/co-working

TRAVEL
- Train
- Buses

**Comment by amyvbenson** [comment]
@iparr https://docs.google.com/document/d/12mn07Z_ChFzcTrbUPj6yhf7JhPezXzOOjcS0cToR_Hc/edit#heading=h.g7i9hzchrz9a

I've missed out hotels because I don't think we have any discount ones and I've no idea what any are like.
