### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by iparr** [frontendnorth/fen#37]
In short term, see document already worked up by @amyvbenson in PDF form. Probably just link to PDF.

Then?…

**Comment by amyvbenson** [comment]
Copy for now:

## Sponsorship

We’re currently offering sponsorship packages for Front End North 2020.  Find out more about our sponsorship packages here (link to pdf) or get in touch at admin@frontendnorth.com.

### Our sponsors

Evolute logo & link to https://www.evoluted.net/web-development

**Comment by iparr** [comment]
Want to consider adding this as a page, but for now the content needs are satisfied.
