### ISSUE TITLE
Cache busting for static assets

### ISSUE THREAD

**Issue by amyvbenson** [frontendnorth/fen#43]
We need to add this as part of the build process to make sure people aren't served out of date assets.

**Comment by iparr** [comment]
Good call. I'll work this into the build process.

Any docs on what Github pages likes here? I'm used to using Nginx.

**Comment by amyvbenson** [comment]
I don't think githb pages cares, it's not doing any build just serving the static pages.

**Comment by iparr** [comment]
For my reference: I can't use strings like `assets/css/all.7634534.css`, I will have to use a query string like `assets/css/all.css?v=7634534`

This isn't ideal and may be the excuse I've needed to experiment with Netlify.

I think I will make the CMS add the strings for us (probably).
